-- Fix generated migration:
-- - Postgres doesn't support ALTER COLUMN ... TYPE serial
-- - Convert existing "one row per candidate" tables into proper one-to-many:
--   drop old PKs on candidateId, add id identity PK, and add FK(candidateId)->candidates(id) with cascade.

ALTER TABLE "candidates"
  ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY;--> statement-breakpoint

ALTER TABLE "certifications" DROP CONSTRAINT IF EXISTS "certifications_pkey";--> statement-breakpoint
ALTER TABLE "education" DROP CONSTRAINT IF EXISTS "education_pkey";--> statement-breakpoint
ALTER TABLE "expericenes" DROP CONSTRAINT IF EXISTS "expericenes_pkey";--> statement-breakpoint
ALTER TABLE "projects" DROP CONSTRAINT IF EXISTS "projects_pkey";--> statement-breakpoint
ALTER TABLE "recommendations" DROP CONSTRAINT IF EXISTS "recommendations_pkey";--> statement-breakpoint
ALTER TABLE "skills" DROP CONSTRAINT IF EXISTS "skills_pkey";--> statement-breakpoint

ALTER TABLE "certifications" ADD COLUMN "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL;--> statement-breakpoint
ALTER TABLE "education" ADD COLUMN "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL;--> statement-breakpoint
ALTER TABLE "expericenes" ADD COLUMN "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL;--> statement-breakpoint
ALTER TABLE "projects" ADD COLUMN "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL;--> statement-breakpoint
ALTER TABLE "recommendations" ADD COLUMN "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL;--> statement-breakpoint
ALTER TABLE "skills" ADD COLUMN "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL;--> statement-breakpoint

ALTER TABLE "certifications" ADD CONSTRAINT "certifications_pkey" PRIMARY KEY ("id");--> statement-breakpoint
ALTER TABLE "education" ADD CONSTRAINT "education_pkey" PRIMARY KEY ("id");--> statement-breakpoint
ALTER TABLE "expericenes" ADD CONSTRAINT "expericenes_pkey" PRIMARY KEY ("id");--> statement-breakpoint
ALTER TABLE "projects" ADD CONSTRAINT "projects_pkey" PRIMARY KEY ("id");--> statement-breakpoint
ALTER TABLE "recommendations" ADD CONSTRAINT "recommendations_pkey" PRIMARY KEY ("id");--> statement-breakpoint
ALTER TABLE "skills" ADD CONSTRAINT "skills_pkey" PRIMARY KEY ("id");--> statement-breakpoint

ALTER TABLE "certifications"
  ADD CONSTRAINT "certifications_candidateId_candidates_id_fk"
  FOREIGN KEY ("candidateId") REFERENCES "public"."candidates"("id")
  ON DELETE cascade ON UPDATE no action;--> statement-breakpoint

ALTER TABLE "education"
  ADD CONSTRAINT "education_candidateId_candidates_id_fk"
  FOREIGN KEY ("candidateId") REFERENCES "public"."candidates"("id")
  ON DELETE cascade ON UPDATE no action;--> statement-breakpoint

ALTER TABLE "expericenes"
  ADD CONSTRAINT "expericenes_candidateId_candidates_id_fk"
  FOREIGN KEY ("candidateId") REFERENCES "public"."candidates"("id")
  ON DELETE cascade ON UPDATE no action;--> statement-breakpoint

ALTER TABLE "projects"
  ADD CONSTRAINT "projects_candidateId_candidates_id_fk"
  FOREIGN KEY ("candidateId") REFERENCES "public"."candidates"("id")
  ON DELETE cascade ON UPDATE no action;--> statement-breakpoint

ALTER TABLE "recommendations"
  ADD CONSTRAINT "recommendations_candidateId_candidates_id_fk"
  FOREIGN KEY ("candidateId") REFERENCES "public"."candidates"("id")
  ON DELETE cascade ON UPDATE no action;--> statement-breakpoint

ALTER TABLE "skills"
  ADD CONSTRAINT "skills_candidateId_candidates_id_fk"
  FOREIGN KEY ("candidateId") REFERENCES "public"."candidates"("id")
  ON DELETE cascade ON UPDATE no action;