CREATE TABLE IF NOT EXISTS "candidates" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "fullName" varchar(255),
  "jobTitle" varchar(255),
  "email" varchar(255),
  "phone" varchar(50),
  "location" varchar(255),
  "gitHubURL" varchar(512),
  "linkedInURL" varchar(512),
  "websiteURL" varchar(512),
  "imageURL" varchar(512),
  "bio" text
);
--> statement-breakpoint

DO $$
BEGIN
  IF to_regclass('public.expericenes') IS NOT NULL AND to_regclass('public.experiences') IS NULL THEN
    ALTER TABLE "expericenes" RENAME TO "experiences";
  END IF;
END $$;
--> statement-breakpoint

CREATE TABLE IF NOT EXISTS "experiences" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "candidateId" integer NOT NULL REFERENCES "candidates"("id") ON DELETE CASCADE,
  "role" varchar(255),
  "company" varchar(255),
  "start_date" timestamp,
  "end_date" timestamp,
  "currentlyWorkHere" boolean,
  "description" text
);
--> statement-breakpoint

CREATE TABLE IF NOT EXISTS "education" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "candidateId" integer NOT NULL REFERENCES "candidates"("id") ON DELETE CASCADE,
  "institution" varchar(255),
  "degree" varchar(255),
  "field" varchar(255),
  "start_date" timestamp,
  "end_date" timestamp,
  "description" text
);
--> statement-breakpoint

CREATE TABLE IF NOT EXISTS "skills" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "candidateId" integer NOT NULL REFERENCES "candidates"("id") ON DELETE CASCADE,
  "skillName" varchar(255),
  "category" integer,
  "level" integer,
  "description" text
);
--> statement-breakpoint

CREATE TABLE IF NOT EXISTS "projects" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "candidateId" integer NOT NULL REFERENCES "candidates"("id") ON DELETE CASCADE,
  "projectTitle" varchar(255),
  "description" text,
  "techStack" text,
  "gitHubURL" varchar(512),
  "liveURL" varchar(512)
);
--> statement-breakpoint

CREATE TABLE IF NOT EXISTS "certifications" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "candidateId" integer NOT NULL REFERENCES "candidates"("id") ON DELETE CASCADE,
  "certificationName" varchar(255),
  "issuer" text,
  "date" timestamp,
  "credentialURL" varchar(512)
);
--> statement-breakpoint

CREATE TABLE IF NOT EXISTS "recommendations" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "candidateId" integer NOT NULL REFERENCES "candidates"("id") ON DELETE CASCADE,
  "name" varchar(255),
  "role" text,
  "recommendation" text
);
--> statement-breakpoint

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'experiences' AND column_name = 'currentltyWorkHere'
  ) THEN
    ALTER TABLE "experiences" RENAME COLUMN "currentltyWorkHere" TO "currentlyWorkHere";
  END IF;
END $$;
--> statement-breakpoint

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'certifications' AND column_name = 'Date'
  ) THEN
    ALTER TABLE "certifications" RENAME COLUMN "Date" TO "date";
  END IF;
END $$;
--> statement-breakpoint

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'certifications' AND column_name = 'credentianlURL'
  ) THEN
    ALTER TABLE "certifications" RENAME COLUMN "credentianlURL" TO "credentialURL";
  END IF;
END $$;
